### ISSUE TITLE
Unoptimized SVGs + download/copy bug

### ISSUE THREAD

**Issue by joshuaptfan** [mono-company/mono-icons#10]
1. Your SVGs appear to be raw exports from Illustrator, as despite their simple appearance, their code is quite long. Consider at least passing your SVG code through an optimizer, or better yet, since they are simple lines, draw them using [SVG strokes](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) instead (your "strokes" are currently filled outlines of strokes).

This is the code for your ["remove" icon](https://github.com/mono-company/mono-icons/blob/master/svg/remove.svg), which is a single horizontal line, being drawn using multiple [Bézier curves](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#B%C3%A9zier_Curves):
```
...
<path d="M4 12C4 11.4477 4.44772 11 5 11H19C19.5523 11 20 11.4477 20 12C20 12.5523 19.5523 13 19 13H5C4.44772 13 4 12.5523 4 12Z" fill="#0D0D0D"/>
...
```

2. When users click on download or copy for an icon, the output contains unnecessary SVG code.

SVG code in your repo:

```
...
<path d="..." fill="#0D0D0D"/>
...
```

SVG code from download/copy:

```
...
<path xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" d="..." fill="#282828"></path>
...
```
`xmlns="http://www.w3.org/2000/svg"` is [not a valid attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg) for path elements, nor is `clip-rule` outside of [clip paths](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-rule). Paths elements should be self-closing instead of given closing tags.

**Comment by Wolfr** [comment]
I believe the code are exports from Figma. We can look into optimizing them, you make some good points!

**Comment by Wolfr** [comment]
@joshuaptfan We used SVGO to optimize all of the icons in version 1.2.4.

Thank you for noting this!
