### ISSUE TITLE
1.1 with 8 new icons needs icons on the site

### ISSUE THREAD

**Issue by Wolfr** [mono-company/mono-icons#17]
We added 8 new icons but they also need to be added to the site.

* sunrise
* sun
* moon
* webcam

@rinxols what else is new?

File:
https://www.figma.com/community/file/887772348681569186

**Comment by rinxols** [comment]
There's 8 new icons:

- backspace
- enter
- sunrise
- webcam
- repeat
- previous
- next
- shuffle

Indeed @Wolfr, they've all been added to the Figma Community file but they're still missing from the site. Who can take care of this?

**Comment by Wolfr** [comment]
@rinxols the website was updated

Figma file is at 1.2.1 and the website is at 1.2.1.

All in sync! If we add more icons, it would be good to keep a list.

👍
