### ISSUE TITLE
Icons alignement with webfont

### ISSUE THREAD

**Issue by jbelien** [mono-company/mono-icons#2]
First things first, great job ! I really love your icons set ! \o/

I migrated one of my projects from Font Awesome to Mono Icons and I love it ...
but the icons are not perfectly aligned with my texts!

You can check it here : https://report.osm.be/
![image](https://user-images.githubusercontent.com/1150563/93342034-22d8b400-f82f-11ea-94d0-9336a62a5809.png)

What would be the best way to fix that alignment ?

Thanks!

**Comment by Wolfr** [comment]
In this case, I would do

```
h1 i {
    position: relative;
    top: 6px;
}
````

For different contexts, a different value will be needed.

**Comment by jbelien** [comment]
> For different contexts, a different value will be needed.

That's what I meant, would there be a way to have something that applies to all (most ?) situation ?
Something that would vertically align to the center of the text in the same element ? or align to the "baseline" ?

To be honest, I don't really know what I'm talking about here (ask @evajacobs :P), but when using Font Awesome webfont (for instance), the icons are "magically" aligned correctly (or at least correctly based on what I "expect").

**Comment by Wolfr** [comment]
I see what you mean, perhaps we should take a look at aligning to the baseline of fonts in a better way.

**Comment by Wolfr** [comment]
On the icon font generator package, there is a `--center` and a `--descent` flag, something we should experiment with.

**Comment by ukaaa** [comment]
I gave `--descent` a try. The results are satisfying. I've made a PR ☝️

`--center` is used for horizontal centering.

**Comment by Wolfr** [comment]
@ukaaa this is indeed satisfying.

@jbelien sorry for letting you wait for 2 months,

These Svelte REPLs demonstrate the fix:

* Correct https://svelte.dev/repl/79de4cd85f6248559476dba9ac309dc5?version=3.29.7
* Bad (old) https://svelte.dev/repl/9875652ea79c46c7a03bc208d171bd4f?version=3.29.7

**Comment by jbelien** [comment]
No worries! Thanks @Wolfr , the update works like a charm 👌

**Comment by Wolfr** [comment]
Haha you already updated it. Nice. I love how the whole icon font generation aspect can live in a package in itself.
