### ISSUE TITLE
Repo is not tied to npm

### ISSUE THREAD

**Issue by Wolfr** [mono-company/mono-icons#4]
Somehow, the repo is not tied to the npm package.

<img src="https://user-images.githubusercontent.com/12690/93347205-1a837780-f835-11ea-95d0-48c696db73df.png" width="400">

**Comment by jbelien** [comment]
If needed, here is my GitHub Actions workflow to publish on NPM + GitHub packages : https://github.com/jbelien/openstreetmap-calendar-widget/blob/master/.github/workflows/npm-publish.yml

**Comment by Wolfr** [comment]
We have been publishing manually using `npm login` and then `npm publish .`, while logged into a `monocompany` npm account. I thought Github might just make the connection between the repo and npm using package.json.

Haven't used Github actions yet.

**Comment by jbelien** [comment]
> I thought Github might just make the connection between the repo and npm using package.json.

Not that I know of!
"Packages" on the right column on the main page of the repository is only for packages published on GitHub Packages.

**Comment by capnmidnight** [comment]
https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages

**Comment by Wolfr** [comment]
This seems a bit complicated compared to manually publishing. I think it will be only worthwhile to set this up if we update the set often.

**Comment by Wolfr** [comment]
I removed the shortcuts on the homepage, we are using npm.

https://www.npmjs.com/package/mono-icons
