### ISSUE TITLE
README: CDN latest version will cause issue with breaking changes

### ISSUE THREAD

**Issue by jbelien** [mono-company/mono-icons#6]
In the [README paragrah CDN](https://github.com/mono-company/mono-icons#cdn), I wouldn't recommend to use `@latest` version in 
```html
<link href="https://unpkg.com/mono-icons@latest/iconfont/icons.css" rel="stylesheet">
````
because if people use `@latest`, any breaking change in your code will break all the websites that are using Mono Icons.
It happened to me yesterday with the namespacing commit (https://github.com/mono-company/mono-icons/commit/a61fe2963c76683c0ad9ea0feb5c76bb88623de3).

I would recommend to use the last version number in the README:
```html
<link href="https://unpkg.com/mono-icons@1.0.5/iconfont/icons.css" rel="stylesheet">
```

And if the version is "fixed", why not add the subresource integrity value (see [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)) ? \o/

**Comment by Wolfr** [comment]
Hmm, good point, I thought this would make it so we never had to update the README, but the icon font generates different stylesheets, so indeed, this causes a breaking change.

**Comment by Wolfr** [comment]
Fixed in https://github.com/mono-company/mono-icons/commit/fe6dac0213158101ddb8959b73efad528edcfb24
