### ISSUE TITLE
Community requests

### ISSUE THREAD

**Issue by Wolfr** [mono-company/mono-icons#7]
Please file any requests here, then we can consider them for future additions to the set.

**Comment by craigsoenen** [comment]
It would be great to have a Compass icon.

**Comment by xavez** [comment]
Here's one from LinkedIn

<img width="484" alt="CleanShot 2020-09-17 at 14 36 10@2x" src="https://user-images.githubusercontent.com/400335/93471073-259cdd00-f8f3-11ea-9ae5-6e77b905f785.png">

**Comment by tnodir** [comment]
Please add also icons for:
- key (as door key)
- application window
- bin empty & full (as recycle bin)
- line-chart (in addition to "bar-chart" icon)
- cog (for options icon)
- database
- network local & global
- map
- piece of puzzle (for plugin icon)
- server (in addition to "computer" & "laptop" icons)

Thanks.

**Comment by schickst** [comment]
Would like the following: 
- sunrise/sunset
- moon/lunar phases (full moon, new moon, first quarter, third quarter)

**Comment by naknode** [comment]
- Whistle
- Flag (Square)

**Comment by emmanuelvacher** [comment]
L

**Comment by philefstat** [comment]
@schickst https://github.com/mono-company/mono-icons/pull/16

**Comment by ukaaa** [comment]
It would be great to have "filled" variants of all icons 🙊 
This way we could use them e.g. for toggles: unfilled is off, filled is on. But it would be a lot of work to make, and almost impossible to automate.

**Comment by Wolfr** [comment]
I see some requests in this HN thread, which I totally did not spot when we released the set: https://news.ycombinator.com/item?id=24564684

**Comment by paddle-to-the-sea** [comment]
It would be great to have a "Save" icon. I'd vote for one of the "3.5 inch floppy" variety.

In any event, thank you for this project!

**Comment by Wolfr** [comment]
<img width="120" alt="Screenshot 2020-12-06 at 11 28 29" src="https://user-images.githubusercontent.com/12690/101277643-30f6fa80-37b6-11eb-8d5c-4bd5e0be0813.png">

Something like this, but in strokes? This one tends to open up philosophical discussions, but I am not against adding it to the set.

**Comment by paddle-to-the-sea** [comment]
> 
> 
> <img alt="Screenshot 2020-12-06 at 11 28 29" width="120" src="https://user-images.githubusercontent.com/12690/101277643-30f6fa80-37b6-11eb-8d5c-4bd5e0be0813.png">
> 
> Something like this, but in strokes? This one tends to open up philosophical discussions, but I am not against adding it to the set.

I was thinking something more along the lines of Susan Kare's Save icon for the Macintosh ([as seen here](https://kareprints.com/products/1984-a-z-on-gray)) or the Save icon from the Carbon icons (search for "floppy" or "save" at [this link](https://www.carbondesignsystem.com/guidelines/icons/library)).

These two show the floppy disk as viewed from above, which I think looks better than icons which show the view from below, as your example does.

In any event, thank you for considering my request and for this project!

**Comment by aljaxus** [comment]
A "script" (terminal / executable) icon would also be a quite nice thing to have.

**Comment by parkersprouse** [comment]
It would be great for there to be a "sign in" icon to pair with the "sign out" icon.

Thanks guys!

**Comment by meduzen** [comment]
👋 I’m using some of your nice icons in a project, and I’d love to have an icon representing a language switcher, like one of these:
![image](https://user-images.githubusercontent.com/9340937/115848614-56faff80-a424-11eb-857f-39ac2cc3c178.png)

([Other examples](https://www.startpage.com/sp/search?q=google+translate+icon&cat=pics).)

Maybe a globe 🌐 could be another addition (some projects require a language switcher, others a country switcher).

Many thanks for your icon set. 👍

**Comment by Wolfr** [comment]
We listened to the community requests in the newest version of Mono icons. We don't have everything that was requested but there are some additions like

* sign out
* save
* sunrise
* sunset
* database
* cog
* application window

You can find the update at the marketing website over at https://icons.mono.company/ .

**Comment by Wolfr** [comment]
I am closing this thread in favor of individual threads to request an icon. If you want to request an icon, please make an individual thread with a screenshot reference such as #20 and #21 .

**Comment by Wolfr** [comment]
BTW @meduzen we recently tackled this problem and made a globe. Here are some new additions to the Figma file that are in the community file but not on the website yet:

<img width="660" alt="CleanShot 2021-06-29 at 14 02 32@2x" src="https://user-images.githubusercontent.com/12690/123793995-a9541300-d8e2-11eb-9051-53b00f8c3e33.png">

We also have a similar icon with the A and the kanji but we have to redraw it.
